#!/bin/sh

# Specify that the image should be transferred using PNG compression.
mimetype="image/png"

# Get the image that's currently in the clipboard and read the URI data.
content=`xclip -selection clipboard -t "$mimetype" -o 2> /dev/null | base64 -w0`

# Check if it was sucessful. This will fail if the item in the clipboard was not
# an image.
if [ -z "$content" ]
then
    echo "Clipboard not recognised as image" >&2
    exit 1
fi

# Format the data and insert it into the clipboard. This is formatted such that
# it can be inserted into the parentheses in markdown like so:
#   ![image](<CLIPBOARD_OUTPUT>)
echo -n "data:$mimetype;base64,$content" | xclip -selection clipboard
